# Generated by Django 4.0.3 on 2022-03-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Atendente',
                'verbose_name_plural': 'Atendentes',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('telefone1', models.CharField(max_length=20, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(max_length=20, verbose_name='Telefone 2')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('data_contato', models.DateTimeField()),
                ('observacoes', models.TextField()),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.atendente')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.curso')),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.marketing')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.polo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.status')),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
            },
        ),
    ]
