# Generated by Django 4.0.3 on 2022-04-16 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Atendente',
                'verbose_name_plural': 'Atendentes',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marketing',
                'verbose_name_plural': 'Marketing',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('data_contato', models.DateField(verbose_name='Data do contato')),
                ('observacoes', models.TextField(verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.atendente', verbose_name='Atendente')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscrito_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inscrito_criado_por', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.curso', verbose_name='Curso')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.periodo', verbose_name='Período')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.polo', verbose_name='Polo')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.situacao', verbose_name='Situação')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Inscrito',
                'verbose_name_plural': 'Inscritos',
            },
        ),
        migrations.CreateModel(
            name='ExAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('data_saida', models.DateField(verbose_name='Data da saída')),
                ('observacoes', models.TextField(verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.atendente', verbose_name='Atendente')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exaluno_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='exaluno_criado_por', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.curso', verbose_name='Curso')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.motivo', verbose_name='Motivo do Cancelamento')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.periodo', verbose_name='Período')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.polo', verbose_name='Polo')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.situacao', verbose_name='Situação')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Ex Aluno',
                'verbose_name_plural': 'Ex Alunos',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('data_contato', models.DateField(verbose_name='Data do contato')),
                ('observacoes', models.TextField(verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.atendente', verbose_name='Atendente')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='candidato_criado_por', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.curso', verbose_name='Curso')),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.marketing', verbose_name='Marketing')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.periodo', verbose_name='Período')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.polo', verbose_name='Polo')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.situacao', verbose_name='Situação')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
    ]
