# Generated by Django 4.0.3 on 2022-03-26 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='atendente',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='atendente', to=settings.AUTH_USER_MODEL, verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_contato',
            field=models.DateField(verbose_name='Data do contato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.marketing', verbose_name='Marketing'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='observacoes',
            field=models.TextField(verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.periodo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='polo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.polo', verbose_name='Polo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.status', verbose_name='Status'),
        ),
    ]
