# Generated by Django 4.0.3 on 2022-08-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='atendimentos',
            field=models.TextField(blank=True, null=True, verbose_name='Atendimentos'),
        ),
        migrations.CreateModel(
            name='AtendimentosAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.candidato')),
            ],
            options={
                'verbose_name': 'Atendimentos dos Aluno',
                'verbose_name_plural': 'Atendimentos dos Alunos',
                'ordering': ['-data'],
            },
        ),
    ]
