# Generated by Django 4.0.3 on 2022-04-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0002_situacaoexaluno_situacaoinscrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exaluno',
            name='ra',
            field=models.CharField(default='0000000', max_length=7, verbose_name='RA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='observacoes',
            field=models.TextField(verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captacao.motivo', verbose_name='Motivo'),
        ),
    ]
