# Generated by Django 4.0.3 on 2022-06-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0003_exaluno_ra_alter_candidato_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exaluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketing',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motivo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='polo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='situacaoexaluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='situacaoinscrito',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='status',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.atendente', verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='marketing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.marketing', verbose_name='Marketing'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.periodo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='polo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.polo', verbose_name='Polo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.atendente', verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.motivo', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.periodo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='polo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.polo', verbose_name='Polo'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.situacaoexaluno', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='atendente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.atendente', verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.periodo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='polo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.polo', verbose_name='Polo'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.situacaoinscrito', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.status', verbose_name='Status'),
        ),
    ]
