# Generated by Django 4.0.3 on 2022-11-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0003_emailfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfile',
            name='subject',
            field=models.CharField(default='Sem título', max_length=200, verbose_name='Assunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailfile',
            name='email',
            field=models.TextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='emailfile',
            name='filename',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
