# Generated by Django 4.0.3 on 2022-06-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0004_atendente_ativo_candidato_ativo_curso_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacaoexaluno',
            options={'verbose_name': 'Situação ExAluno', 'verbose_name_plural': 'Situação ExAlunos'},
        ),
        migrations.AlterModelOptions(
            name='situacaoinscrito',
            options={'verbose_name': 'Situação Inscrito', 'verbose_name_plural': 'Situação Inscritos'},
        ),
    ]
