# Generated by Django 4.0.3 on 2022-06-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0005_alter_situacaoexaluno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_campus', models.CharField(max_length=100, verbose_name='NomCampus')),
                ('nom_curso_grupo', models.CharField(max_length=100, verbose_name='NomCursoGrupo')),
                ('cod_curso', models.PositiveIntegerField(verbose_name='CodCurso')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('dsc_modalidade', models.CharField(max_length=20, verbose_name='DscModalidade')),
                ('serie', models.PositiveSmallIntegerField(verbose_name='Serie')),
                ('semana', models.CharField(max_length=15, verbose_name='Semana')),
                ('cod_ra', models.PositiveIntegerField(verbose_name='CodRA')),
                ('nom_aluno', models.CharField(max_length=255, verbose_name='NomAluno')),
                ('dat_matr', models.DateField(verbose_name='DatMatr')),
                ('status_aluno', models.CharField(max_length=30, verbose_name='StatusAluno')),
                ('turma_ano_ingresso', models.CharField(max_length=50, verbose_name='TurmaAnoIngresso')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefone1', models.CharField(max_length=15, verbose_name='TelefoneCel1')),
                ('telefone2', models.CharField(max_length=15, verbose_name='TelefoneCel2')),
                ('telefone_res', models.CharField(max_length=15, verbose_name='TelefoneRes')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('bolsista', models.CharField(max_length=5, verbose_name='Bolsista')),
                ('dat_ingresso', models.DateField(verbose_name='Dat_ingresso')),
                ('data_prev_termino', models.DateField(verbose_name='DataPrevTermino')),
                ('ativo', models.BooleanField(default=True)),
                ('periodos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='captacao.periodo', verbose_name='Períodos')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
