# Generated by Django 4.0.3 on 2022-06-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0006_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TelefoneCel1'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TelefoneCel2'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone_res',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TelefoneRes'),
        ),
    ]
