# Generated by Django 4.0.3 on 2022-06-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0007_alter_aluno_email_alter_aluno_telefone1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='periodos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodos',
            field=models.ManyToManyField(related_name='periodos', to='captacao.periodo', verbose_name='Períodos'),
        ),
    ]
