# Generated by Django 4.0.3 on 2022-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0008_remove_aluno_periodos_aluno_periodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(default='', verbose_name='Observacoes'),
            preserve_default=False,
        ),
    ]
