# Generated by Django 4.0.3 on 2022-06-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0009_aluno_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nom_campus_abrev',
            field=models.CharField(default='', max_length=50, verbose_name='NomCampusAbrev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nom_curso_grupo_abrev',
            field=models.CharField(default='', max_length=50, verbose_name='NomCursoGrupoAbrev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma_ano_ingresso_abrev',
            field=models.CharField(default='', max_length=20, verbose_name='TurmaAnoIngressoAbrev'),
            preserve_default=False,
        ),
    ]
