# Generated by Django 4.0.3 on 2022-06-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0010_aluno_nom_campus_abrev_aluno_nom_curso_grupo_abrev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nom_campus_abrev',
            field=models.CharField(editable=False, max_length=50, verbose_name='NomCampusAbrev'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_curso_grupo_abrev',
            field=models.CharField(editable=False, max_length=50, verbose_name='NomCursoGrupoAbrev'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma_ano_ingresso_abrev',
            field=models.CharField(editable=False, max_length=20, verbose_name='TurmaAnoIngressoAbrev'),
        ),
    ]
