# Generated by Django 4.0.3 on 2022-06-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0012_alter_aluno_nom_campus_alter_aluno_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('nome_abrev', models.CharField(editable=False, max_length=50, verbose_name='NomeAbrev')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='nome_abrev',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='NomeAbrev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polo',
            name='nome_abrev',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='NomeAbrev'),
            preserve_default=False,
        ),
    ]
