# Generated by Django 4.0.3 on 2022-07-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0014_aluno_dsc_modalidade_abrev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dsc_modalidade_abrev',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='captacao.modalidade', verbose_name='DscModalidadeAbrev'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_campus_abrev',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='captacao.polo', verbose_name='NomCampusAbrev'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_curso_grupo_abrev',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='captacao.curso', verbose_name='NomCursoGrupoAbrev'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='exaluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='nome',
            field=models.CharField(max_length=10, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='polo',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='polo',
            name='nome_abrev',
            field=models.CharField(max_length=50, unique=True, verbose_name='NomeAbrev'),
        ),
        migrations.AlterField(
            model_name='situacaoexaluno',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='situacaoinscrito',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome'),
        ),
    ]
