# Generated by Django 4.0.3 on 2022-07-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0015_alter_aluno_dsc_modalidade_abrev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dsc_modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modalidade', to='captacao.modalidade', verbose_name='DscModalidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dsc_modalidade_abrev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modalidade_abrev', to='captacao.modalidade', verbose_name='DscModalidadeAbrev'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus', to='captacao.polo', verbose_name='NomCampus'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_campus_abrev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campus_abrev', to='captacao.polo', verbose_name='NomCampusAbrev'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_curso_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso', to='captacao.curso', verbose_name='NomCursoGrupo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nom_curso_grupo_abrev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso_abrev', to='captacao.curso', verbose_name='NomCursoGrupoAbrev'),
        ),
    ]
