# Generated by Django 4.0.3 on 2022-07-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0016_alter_aluno_dsc_modalidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='dsc_modalidade_abrev',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nom_campus_abrev',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nom_curso_grupo_abrev',
        ),
    ]
