# Generated by Django 4.0.3 on 2022-07-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0017_remove_aluno_dsc_modalidade_abrev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome_abrev',
            field=models.CharField(max_length=50, unique=True, verbose_name='NomeAbrev'),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='nome_abrev',
            field=models.CharField(max_length=50, unique=True, verbose_name='NomeAbrev'),
        ),
    ]
