# Generated by Django 4.0.3 on 2022-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0018_alter_curso_nome_abrev_alter_modalidade_nome_abrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='periodos',
            field=models.ManyToManyField(blank=True, null=True, related_name='periodos', to='captacao.periodo', verbose_name='Períodos'),
        ),
    ]
